name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1', '8.2']
        stability: [prefer-lowest, prefer-stable]
        include:
          - php: '8.1'
            flags: "--ignore-platform-req=php"
            stability: prefer-stable

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Execute tests
        continue-on-error: ${{ matrix.php > 8 }}
        run: composer run test
